#-------------------------------
# General Site Settings
title: Chess
logo: # You can add own logo. For example '/images/logo.png'.
description: Chess – Senior Chess Improver.
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Egbert Schroeer
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Senior Chess Improver
  description: Thoughts, stories and ideas - Chesspunks
  image: '/images/beachchess.jpg'

#  image: '/images/sunset.jpg'

#-------------------------------
# Contact Settings
contact:
  email: chesslife@myvortexcloud.com # Add your email for contact form
  description: Norlin comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
# - {icon: "ion-logo-twitter", link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# - {icon: "ion-logo-instagram", link: "https://instagram.com"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-youtube", link: "https://youtube.com"}
- {icon: "ion-logo-github", link: "https://github.com/Egbert-Azure"}
# - {icon: "ion ion-logo-vimeo", link: "https://vimeo.com/"}
- {icon: "ion-logo-mastodon", link: "https://mastodon.online/@EgbertS"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/egbert-schroeer/"}
- {icon: "ion-logo-rss", link: "https://follow.it/senior-chess-improver?leanpub"}
#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-egbert-azure-github-io # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# collections_dir: _collections
collections:
  puzzles:
    output: true
    permalink: /puzzles/:title/
  games:
    output: true
    permalink: /games/:title/
  tournaments:
    output: true
    permalink: /tournaments/:title/

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed