#-------------------------------
# Site Settings
title: Chess
logo: # You can add own logo. For example '/images/logo.png'.
description: Chess – Senior Chess Improver.


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'Tournaments'
      url: '/tournaments/'
    - title: 'Puzzles'
      url: '/puzzles/' 
    - title: 'About'
      url: '/about/'
    - title: 'Contact Me'
      url: '/contact/'

#-------------------------------
# Author Settings
author:
  name: Egbert Schroeer
  avatar: '/images/15.jpg'
#-------------------------------
# Hero Settings
hero:
  title: Senior Chess Improver
  description: Thoughts, stories and ideas - Chesspunks
  image: '/images/beachchess.jpg'

#  image: '/images/sunset.jpg'


#-------------------------------
# Contact Settings
contact: 
  email: xrgndwdg # Add your email for contact form
  description: The Senior Chess Improver Website - sharing learnings, findings and experiences. Questions, contributions, feedback - you've come to the right place! # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:
# - {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
# - {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com"}
# - {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
# - {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
# - {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
# - {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com"}
# - {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com/"}
- {icon: "fa-solid fa-rss", name: "Follow-it", link: "https://follow.it/senior-chess-improver?leanpub"}
- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.online/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/Egbert-Azure"}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/egbert-schroeer/"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-egbert-azure-github-io # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp:  # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join